### ISSUE TITLE
UnknownFormatConversionException

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#10]
Fatal Exception: java.util.UnknownFormatConversionException: Conversion: ,
       at java.util.Formatter$FormatToken.unknownFormatConversionException(Formatter.java:1399)
       at java.util.Formatter$FormatToken.checkFlags(Formatter.java:1336)
       at java.util.Formatter.transform(Formatter.java:1442)
       at java.util.Formatter.doFormat(Formatter.java:1081)
       at java.util.Formatter.format(Formatter.java:1042)
       at java.util.Formatter.format(Formatter.java:1011)
       at java.lang.String.format(String.java:1803)
       at java.lang.String.format(String.java:1777)
       at andicar.n.persistence.viewadapter.RefuelViewAdapter.cursorViewBinder(RefuelViewAdapter.java:147)
       at andicar.n.persistence.viewadapter.BaseViewAdapter.onBindViewHolder(BaseViewAdapter.java:148)
       at andicar.n.persistence.viewadapter.BaseViewAdapter.onBindViewHolder(BaseViewAdapter.java:75)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6400)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6433)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5377)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5640)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
       at android.widget.FrameLayout.onLayout(FrameLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
       at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1389)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:868)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
       at android.widget.FrameLayout.onLayout(FrameLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java)
       at android.widget.LinearLayout.onLayout(LinearLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
       at android.widget.FrameLayout.onLayout(FrameLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java)
       at android.widget.LinearLayout.onLayout(LinearLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
       at android.widget.FrameLayout.onLayout(FrameLayout.java)
       at android.view.View.layout(View.java)
       at android.view.ViewGroup.layout(ViewGroup.java)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
       at android.view.Choreographer.doCallbacks(Choreographer.java)
       at android.view.Choreographer.doFrame(Choreographer.java)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
       at android.os.Handler.handleCallback(Handler.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by mkeresztes** [comment]
Fixed in 17.08-02
