### ISSUE TITLE
Android O: fatal Exception: android.os.FileUriExposedException

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#16]
```
Fatal Exception: android.os.FileUriExposedException: file:///storage/emulated/0/andicar/reports/MileageReport_201710120720171012070822999.csv exposed beyond app through ClipData.Item.getUri()
       at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
       at android.net.Uri.checkFileUriExposed(Uri.java:2348)
       at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
       at android.app.Activity.startActivityForResult(Activity.java:4472)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:54)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
       at android.app.Activity.startActivityForResult(Activity.java:4430)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:708)
       at android.app.Activity.startActivity(Activity.java:4791)
       at android.app.Activity.startActivity(Activity.java:4759)
       at andicar.n.activity.CommonListActivity.createReport(CommonListActivity.java:1053)
       at andicar.n.activity.CommonListActivity.run(CommonListActivity.java:1369)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by mkeresztes** [comment]
fixed in 17.10-2
