### ISSUE TITLE
Non-fatal Exception: java.io.FileNotFoundException: /storage/emulated/0/andicar/log/FBJobServiceTD.log (Permission denied)

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#17]
```
Non-fatal Exception: java.io.FileNotFoundException: /storage/emulated/0/andicar/log/FBJobServiceTD.log (Permission denied)
       at java.io.FileOutputStream.open(FileOutputStream.java)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
       at java.io.FileWriter.<init>(FileWriter.java:107)
       at andicar.n.utils.LogFileWriter.<init>(LogFileWriter.java:19)
       at andicar.n.service.FBJobService.onStartJob(FBJobService.java:57)
       at com.firebase.jobdispatcher.JobService.start(JobService.java:125)
       at com.firebase.jobdispatcher.JobServiceConnection.onServiceConnected(JobServiceConnection.java:66)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1516)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1544)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by mkeresztes** [comment]
fixed in 17.10-3
