### ISSUE TITLE
NullPointerException on SQLiteDatabase.query or SQLiteOpenHelper.close()

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#18]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(boolean, java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
       at andicar.n.persistence.DBAdapter.fetchRecord(DBAdapter.java:309)
       at andicar.n.service.ToDoNotificationJob.checkAndNotifyForToDo(ToDoNotificationJob.java:106)
       at andicar.n.service.ToDoNotificationJob.access$100(ToDoNotificationJob.java:22)
       at andicar.n.service.ToDoNotificationJob$1.run(ToDoNotificationJob.java:62)
       at java.lang.Thread.run(Thread.java:761)
```
or
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.database.sqlite.SQLiteOpenHelper.close()' on a null object reference
       at andicar.n.persistence.DB.close(DB.java:996)
       at andicar.n.service.ToDoNotificationJob$1.run(ToDoNotificationJob.java:66)
       at java.lang.Thread.run(Thread.java:776)
```

**Comment by mkeresztes** [comment]
Released in 17.12
