### ISSUE TITLE
Utils.showInfoDialog - Calling startActivity() from outside of an Activity

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#19]
```
Fatal Exception: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
       at android.app.ContextImpl.startActivity(ContextImpl.java)
       at android.app.ContextImpl.startActivity(ContextImpl.java)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java)
       at andicar.n.utils.Utils.showInfoDialog(Utils.java:379)
       at andicar.n.activity.miscellaneous.FileListActivity.run(FileListActivity.java:245)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by mkeresztes** [comment]
Released in 17.12
