### ISSUE TITLE
Fabric reported - Unmarshalling unknown type code

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#2]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.andicar2.activity/org.andicar2.activity.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@ee2b1af: Unmarshalling unknown type code 7209057 at offset 1340
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by java.lang.RuntimeException: Parcel android.os.Parcel@ee2b1af: Unmarshalling unknown type code 7209057 at offset 1340
       at android.os.Parcel.readValue(Parcel.java:2453)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2808)
       at android.os.Parcel.readSparseArray(Parcel.java:2077)
       at android.os.Parcel.readValue(Parcel.java:2431)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
       at android.os.BaseBundle.unparcel(BaseBundle.java:269)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:910)
       at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2240)
       at android.app.Activity.onRestoreInstanceState(Activity.java:1126)
       at android.app.Activity.performRestoreInstanceState(Activity.java:1081)
       at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1182)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2897)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by mkeresztes** [comment]
Fixed
