### ISSUE TITLE
NullPointerException on BackupRestorePreferenceFragment.showGDriveFolderSelector

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#20]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.app.Activity.getString(int)' on a null object reference
       at andicar.n.activity.preference.PreferenceActivity$BackupRestorePreferenceFragment.showGDriveFolderSelector(PreferenceActivity.java:909)
       at andicar.n.activity.preference.PreferenceActivity$BackupRestorePreferenceFragment.onConnected(PreferenceActivity.java:1471)
       at com.google.android.gms.common.internal.zzad.zzk(Unknown Source)
       at com.google.android.gms.common.api.internal.zzbd.zzj(Unknown Source)
       at com.google.android.gms.common.api.internal.zzar.zzahc(Unknown Source)
       at com.google.android.gms.common.api.internal.zzar.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzbl.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzw.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzab.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzn.zzajn(Unknown Source)
       at com.google.android.gms.common.internal.zze.zzs(Unknown Source)
       at com.google.android.gms.common.internal.zzi.zzajo(Unknown Source)
       at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5845)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

**Comment by mkeresztes** [comment]
Released in 17.12
