### ISSUE TITLE
RT Exception when Google Account Chooser is not available - e.g Amazon devices

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#22]
```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.google.android.gms.common.account.CHOOSE_ACCOUNT pkg=com.google.android.gms (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1797)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1634)
       at android.app.Activity.startActivityFromFragment(Activity.java:4365)
       at android.app.Fragment.startActivityForResult(Fragment.java:1100)
       at android.app.Fragment.startActivityForResult(Fragment.java:1084)
       at andicar.n.activity.preference.PreferenceActivity$BackupRestorePreferenceFragment.showGoogleAccountChooser(PreferenceActivity.java:1082)
       at andicar.n.activity.preference.PreferenceActivity$BackupRestorePreferenceFragment.access$700(PreferenceActivity.java:559)
       at andicar.n.activity.preference.PreferenceActivity$BackupRestorePreferenceFragment$7.onPreferenceChange(PreferenceActivity.java:806)
       at android.preference.Preference.callChangeListener(Preference.java:929)
       at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:64)
       at android.preference.Preference.performClick(Preference.java:984)
       at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
       at android.widget.AdapterView.performItemClick(AdapterView.java:305)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1166)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3073)
       at android.widget.AbsListView.onTouchUp(AbsListView.java:3907)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:3666)
       at android.view.View.dispatchTouchEvent(View.java:8744)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2412)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2105)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2413)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1748)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2758)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2374)
       at android.view.View.dispatchPointerEvent(View.java:8939)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4191)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4045)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3736)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3627)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3793)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3627)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5910)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5883)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5850)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6000)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:122)
       at android.app.ActivityThread.main(ActivityThread.java:5491)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by mkeresztes** [comment]
Released in 17.12
