### ISSUE TITLE
Activity  context requires the FLAG_ACTIVITY_NEW_TASK

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#23]
```
Fatal Exception: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
       at android.app.ContextImpl.startActivity(ContextImpl.java:953)
       at android.app.ContextImpl.startActivity(ContextImpl.java:940)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:290)
       at andicar.n.utils.Utils.showInfoDialog(Utils.java:379)
       at andicar.n.activity.miscellaneous.FileListActivity$1.onItemClick(FileListActivity.java:202)
       at android.widget.AdapterView.performItemClick(AdapterView.java:298)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:2788)
       at android.widget.AbsListView$1.run(AbsListView.java:3499)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5121)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by mkeresztes** [comment]
Released in 17.12
