### ISSUE TITLE
java.lang.RuntimeException in FileUtils.copyFile

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#25]
```
Non-fatal Exception: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
       at android.os.Handler.<init>(Handler.java:200)
       at android.os.Handler.<init>(Handler.java:114)
       at android.widget.Toast$TN$2.<init>(Toast.java:336)
       at android.widget.Toast$TN.<init>(Toast.java:336)
       at android.widget.Toast.<init>(Toast.java:103)
       at android.widget.Toast.makeText(Toast.java:256)
       at andicar.n.utils.FileUtils.copyFile(FileUtils.java:496)
       at andicar.n.utils.FileUtils.copyFile(FileUtils.java:454)
       at andicar.n.utils.FileUtils.backupDb(FileUtils.java:301)
       at andicar.n.service.BackupJob$1.run(BackupJob.java:82)
       at java.lang.Thread.run(Thread.java:761)
```
Line 501: Toast toast = Toast.makeText(ctx, "Error: " + e.getMessage(), Toast.LENGTH_LONG);

**Comment by mkeresztes** [comment]
fixed in 18.01
