### ISSUE TITLE
NullPointerException on RefuelEditFragment.java:593 (no uom conversion)

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#30]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.math.BigDecimal.toString()' on a null object reference
       at andicar.n.activity.fragment.RefuelEditFragment.saveData(RefuelEditFragment.java:593)
       at andicar.n.activity.fragment.BaseEditFragment.actionDone(BaseEditFragment.java:991)
       at andicar.n.activity.fragment.BaseEditFragment.onOptionsItemSelected(BaseEditFragment.java:879)
       at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2394)
       at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3326)
       at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:386)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
       at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
       at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
       at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
       at android.view.View.performClick(View.java:6213)
       at android.widget.TextView.performClick(TextView.java:11074)
       at android.view.View$PerformClick.run(View.java:23645)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by mkeresztes** [comment]
released in 18.03
