### ISSUE TITLE
Fabric - Attempt to invoke virtual method 'java.io.Writer java.io.Writer.append(java.lang.CharSequence)' on a null object reference

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#32]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Writer java.io.Writer.append(java.lang.CharSequence)' on a null object reference
       at andicar.n.service.GPSTrackService.appendGOPTrackPoint(GPSTrackService.java:968)
       at andicar.n.service.GPSTrackService.access$2000(GPSTrackService.java:68)
       at andicar.n.service.GPSTrackService$AndiCarLocationListener.onLocationChanged(GPSTrackService.java:1127)
       at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
       at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
       at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6165)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by mkeresztes** [comment]
published in 13.03-3
