### ISSUE TITLE
Fabric - Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.rawQuery(java.lang.String, java.lang.String[])' on a null object reference

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#33]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.rawQuery(java.lang.String, java.lang.String[])' on a null object reference
       at andicar.n.persistence.DBAdapter.execSelectSql(DBAdapter.java:297)
       at andicar.n.persistence.DBAdapter.getCarLastMileageIndex(DBAdapter.java:1649)
       at andicar.n.activity.fragment.GPSTrackControllerFragment.setCarId(GPSTrackControllerFragment.java:139)
       at andicar.n.activity.fragment.GPSTrackControllerFragment.restoreState(GPSTrackControllerFragment.java:357)
       at andicar.n.activity.fragment.GPSTrackControllerFragment.access$200(GPSTrackControllerFragment.java:52)
       at andicar.n.activity.fragment.GPSTrackControllerFragment$1.onServiceConnected(GPSTrackControllerFragment.java:99)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1499)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1527)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6374)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mkeresztes** [comment]
published in 13.03-3
