### ISSUE TITLE
Fabric reported - Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#4]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.andicar2.activity/org.andicar2.activity.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@62644e0: Unmarshalling unknown type code 7209057 at offset 1340
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.RuntimeException: Parcel android.os.Parcel@62644e0: Unmarshalling unknown type code 7209057 at offset 1340
       at android.os.Parcel.readValue(Parcel.java:2340)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2675)
       at android.os.Parcel.readSparseArray(Parcel.java:1967)
       at android.os.Parcel.readValue(Parcel.java:2321)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
       at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2326)
       at android.app.Activity.onRestoreInstanceState(Activity.java:1164)
       at android.app.Activity.performRestoreInstanceState(Activity.java:1109)
       at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1191)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3226)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by mkeresztes** [comment]
Duplocate of issue #2
