### ISSUE TITLE
OutOfMemoryError in SendGMailTask

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#8]
```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
Caused by java.lang.OutOfMemoryError
       at com.google.api.client.repackaged.org.apache.commons.codec.binary.BaseNCodec.resizeBuffer(BaseNCodec.java:177)
       at com.google.api.client.repackaged.org.apache.commons.codec.binary.BaseNCodec.ensureBufferSize(BaseNCodec.java:190)
       at com.google.api.client.repackaged.org.apache.commons.codec.binary.Base64.encode(Base64.java:369)
       at com.google.api.client.repackaged.org.apache.commons.codec.binary.BaseNCodec.encode(BaseNCodec.java:340)
       at com.google.api.client.repackaged.org.apache.commons.codec.binary.Base64.encodeBase64(Base64.java:657)
       at com.google.api.client.repackaged.org.apache.commons.codec.binary.Base64.encodeBase64(Base64.java:622)
       at com.google.api.client.repackaged.org.apache.commons.codec.binary.Base64.encodeBase64URLSafeString(Base64.java:578)
       at com.google.api.client.util.Base64.encodeBase64URLSafeString(Base64.java:79)
       at andicar.n.utils.SendGMailTask.sendGMail(SendGMailTask.java:196)
       at andicar.n.utils.SendGMailTask.doInBackground(SendGMailTask.java:123)
       at andicar.n.utils.SendGMailTask.doInBackground(SendGMailTask.java:63)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by mkeresztes** [comment]
Fixed in 17.08

**Comment by mkeresztes** [comment]
not fixed. it still occurs

**Comment by mkeresztes** [comment]
Can't fix. Use GDrive for destination to avoid this error
