### ISSUE TITLE
GoogleAuthException: UNREGISTERED_ON_API_CONSOLE

### ISSUE THREAD

**Issue by mkeresztes** [mkeresztes/AndiCar#9]
com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAuthIOException
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:301)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at andicar.n.utils.SendGMailTask.sendGMail(SendGMailTask.java:213)
	at andicar.n.utils.SendGMailTask.doInBackground(SendGMailTask.java:129)
	at andicar.n.utils.SendGMailTask.doInBackground(SendGMailTask.java:62)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)
Caused by: com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
	at com.google.android.gms.auth.zze.zzy(Unknown Source)
	at com.google.android.gms.auth.zzd.zza(Unknown Source)
	at com.google.android.gms.auth.zzd.zzb(Unknown Source)
	at com.google.android.gms.auth.zzd.getToken(Unknown Source)
	at com.google.android.gms.auth.zzd.getToken(Unknown Source)
	at com.google.android.gms.auth.zzd.getToken(Unknown Source)
	at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:269)
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:294)
	... 13 more

**Comment by mkeresztes** [comment]
Fixed in 17.08-02
